### ISSUE TITLE
OT: TypeScript

### ISSUE THREAD

**Issue by tredondo** [daniel-brenot/node-binance-fast#3]
Hi Daniel, I noticed you were interested in the [ib-tws-api](https://github.com/maxicus/ib-tws-api) library, and I'm more than willing to solve issue #6 you pointed out there by converting the project to TypeScript and documenting the methods (I've already started work on the latter). I could use some support re. TypeScript issue #15 if you don't mind. I assume you do use IDEs on a regular basis :)

**Comment by daniel-brenot** [comment]
You can look at the merge request on that project where i pushed essentially a full typescript conversion if i remember correctly. It was closed because the library author is a bit ridiculous. Side note, please don't open an issue on a separate repo of mine to contact me. You can reach me directly using my email on my github account, it should be public.
